name: Build and Test v2

on:
  push:
  # pull-request:
  #   types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: ğŸ— Install Yarn
        run: npm install -g yarn

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸ— Setup expo
        uses: expo/expo-github-action@v7
        with:
          token: by0arXS5Je0QCcznuzHG-WRnQlT8Wb7-8VSa4ay-
          expo-version: latest
          eas-version: latest
          expo-cache: true
          eas-cache: true
      
      - name: ğŸ— Setup expo-cli
        run: npm install -g expo-cli

      - name: ğŸš€ Build app
        env:
          EXPO_TOKEN: by0arXS5Je0QCcznuzHG-WRnQlT8Wb7-8VSa4ay-
        run: |
         npm run android
      
      # - name: ğŸ“¦ Deploy app
      #   run: eas deploy


