name: Build iOS

on:
  # push:
  pull-request:
  #   types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: ğŸ— Install project dependencies
        run: |
          npm i

      - name: ğŸ— Install pod dependencies
        run: pod install
        working-directory: ios

      - name: Build iOS (debug)
        run: ""
